cvm-version: 0.10.7
cpus: 4
memory: 4096

networks:
  web:
    egress: open

containers:
  - name: "secret-consumer"
    image: "ghcr.io/tinfoilsh/confidential-debug-secret-consumer@sha256:e9284817649b647465d8d365402edff36e3b9c54550e983ce23aba2f42ae8e33" # v0.2.0
    restart: always
    networks: [web]
    env:
      - BUCKETS_URL: "http://buckets:9000"
      - STORAGE_URL: "https://secret-storage.tinfoil.containers.tinfoil.dev"
      - DATABASE_HOST: "db-demo-storage.tinfoil.dev"
      - DATABASE_DB: "secret_storage"
      - DATABASE_USER: "storage"
      - DOMAIN
    secrets:
      - DATABASE_PASSWORD
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8089/health"]
      interval: 30s
      timeout: 5s
      start_period: 5m

  - name: "buckets"
    image: "ghcr.io/tinfoilsh/tinfoil-buckets-sidecar@sha256:a0f5fd6a3dbdb0a95799ae687e127bb544b7998221458ae1face3fc8c3f43f30"
    restart: always
    networks: [web]
    env:
      - PORT: "9000"
      - BUCKET: "demo-secret-storage"
      - AWS_REGION: "us-east-2"
      - MULTITENANT: "true"
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

shim:
  listen-port: 443
  upstream-port: 8089
  paths:
    - /health
    - /receive
    - /inventory
    - /consume
